version: '3.8'
services:
  db:
    container_name: db
    # 通常imageのversion指定は、latestを用いない（buildのタイミングによってversionが変化する可能性があるため）
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm run build && npm run start"
    ports:
      - "4000:4000"
    depends_on:
      - db
  browser-app:
    container_name: browser-app
    restart: always
    build:
      context: ./browser-app
      dockerfile: Dockerfile
    volumes:
      - ./browser-app:/usr/src/app
    command: sh -c "npm start"
#    command: sh -c "npm run build && cd build && npx serve -p 3000" # 開発時の効率を上げるため、コメントアウト
    ports:
      - "3000:3000"
    depends_on:
      - api
